apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "smart-city.labels" . | nindent 4 }}
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
