apiVersion: v2
name: smart-city
description: Smart City Traffic Optimization Platform — umbrella chart
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Yousef Hasan Hamda
    email: yousef123hamda@gmail.com
